apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hello-prod
resources:
  - ../../base
labels:
  - pairs:
      env: prod
    includeTemplates: true
patches:
  - path: replicas-patch.yaml
